### ISSUE TITLE
ValueError: Shape must be rank 4 but is rank 5 

### ISSUE THREAD

**Issue by Praveen-Nerhethil** [vardanagarwal/Proctoring-AI#18]
Please help me to fix the error.
Traceback (most recent call last):
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 4 but is rank 5 for 'yolo_conv_1/conv2d_59/Conv2D' (op: 'Conv2D') with input shapes: [2,?,?,?,512], [1,1,512,256].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    yolo = YoloV3()
  File "C:\Users\IOT\Documents\Proctoring-AI-master\yolo_helper.py", line 301, in YoloV3
    x = YoloConv(256, name='yolo_conv_1')((x, x_61))
  File "C:\Users\IOT\Documents\Proctoring-AI-master\yolo_helper.py", line 208, in yolo_conv
    return Model(inputs, x, name=name)(x_in)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 815, in call
    mask=masks)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1002, in _run_internal_graph
    output_tensors = layer.call(computed_tensor, **kwargs)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 208, in __call__
    name=self.name)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1112, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)
  File "C:\Users\IOT\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 4 but is rank 5 for 'yolo_conv_1/conv2d_59/Conv2D' (op: 'Conv2D') with input shapes: [2,?,?,?,512], [1,1,512,256].

**Comment by vardanagarwal** [comment]
Please confirm that your TensorFlow version is > 2.

**Comment by Praveen-Nerhethil** [comment]
Thanks for your support.
