### ISSUE TITLE
Failed to run eye_tracker.py

### ISSUE THREAD

**Issue by mchen07** [vardanagarwal/Proctoring-AI#38]
When I run eye_tracker.py from lastest trunk, got the following error

Traceback (most recent call last):
  File "eye_tracker.py", line 154, in <module>
    landmark_model = get_landmark_model()
  File "/Users/mnchen/dev/ML/gaze_demo/Proctoring-AI/face_landmarks.py", line 30, in get_landmark_model
    model = keras.models.load_model(saved_model)
  File "/Users/mnchen/dev/ML/gaze_demo/gaze_demo/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/Users/mnchen/dev/ML/gaze_demo/gaze_demo/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 130, in load
    _read_legacy_metadata(object_graph_def, metadata)
  File "/Users/mnchen/dev/ML/gaze_demo/gaze_demo/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 179, in _read_legacy_metadata
    node_paths = _generate_object_paths(object_graph_def)
  File "/Users/mnchen/dev/ML/gaze_demo/gaze_demo/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 204, in _generate_object_paths
    for reference in object_graph_def.nodes[current_node].children:
IndexError: list index (0) out of range

**Comment by vardanagarwal** [comment]
Please have a look at #34. I have started an additional issue #40, and will try to update it to support Tensorflow 2.4.
