### ISSUE TITLE
IndexError: list index (0) out of range

### ISSUE THREAD

**Issue by shabnam99** [vardanagarwal/Proctoring-AI#48]
I have tried to correct all the syntax which could throw the error but it still shows the index error. Can anyone help me regarding this?
this is the following error I am facing:

Traceback (most recent call last):
  File "mouth_opening_detector.py", line 13, in <module>
    landmark_model = get_landmark_model()
  File "/Users/shabnamsandhi/Desktop/Proctoring-AI-master/face_landmarks.py", line 30, in get_landmark_model
    model = keras.models.load_model(saved_model)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 130, in load
    _read_legacy_metadata(object_graph_def, metadata)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 179, in _read_legacy_metadata
    node_paths = _generate_object_paths(object_graph_def)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 204, in _generate_object_paths
    for reference in object_graph_def.nodes[current_node].children:
IndexError: list index (0) out of range

**Comment by vardanagarwal** [comment]
Please have a look at the issue #40.
