### ISSUE TITLE
No yolov3.weights file exist?

### ISSUE THREAD

**Issue by ywchang0504** [vardanagarwal/Proctoring-AI#6]
Hi:
  try to run main.py but got error, could you please help to check?

D:\project\opencv\Proctoring-AI>python main.py
D:\python\3.7.7\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
D:\python\3.7.7\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
D:\python\3.7.7\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)
2020-07-07 10:34:13.058164: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-07 10:34:13.063303: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-07-07 10:34:31.033803: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-07-07 10:34:31.045068: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-07 10:34:31.052288: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-FCB4CGP
2020-07-07 10:34:31.056705: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-FCB4CGP
2020-07-07 10:34:31.068621: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-07 10:34:31.285820: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1f307b30cf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-07 10:34:31.290499: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    load_darknet_weights(yolo, 'yolov3.weights')
  File "D:\project\opencv\Proctoring-AI\yolo_helper.py", line 35, in load_darknet_weights
    wf = open(weights_file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'yolov3.weights'

**Comment by vardanagarwal** [comment]
Please refer to this article https://medium.com/analytics-vidhya/count-people-in-webcam-using-yolov3-tensorflow-f407679967d5?source=friends_link&sk=95ae7a010eeef429a407a7a2de2ff8ec 

In this I have mentioned the way to download it you can follow that.

**Comment by vardanagarwal** [comment]
You can download them by running this code in python:

```
import wget
url = 'https://pjreddie.com/media/files/yolov3.weights'
yolov3 = wget.download(url, out='yolov3.weights')
```

Or you can download from [here](https://pjreddie.com/media/files/yolov3.weights) and place it in the working directory.
